from PyQt5 import QtCore, QtGui, QtWidgets


class DBWindow(object):
    def setupUi(self, DBWindow):
        DBWindow.setObjectName("DBWindow")
        DBWindow.resize(1222, 853)
        self.centralwidget = QtWidgets.QWidget(DBWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(980, 300, 221, 381))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.btDelete = QtWidgets.QPushButton(self.groupBox)
        self.btDelete.setGeometry(QtCore.QRect(70, 100, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btDelete.setFont(font)
        self.btDelete.setObjectName("btDelete")
        self.btUpdate = QtWidgets.QPushButton(self.groupBox)
        self.btUpdate.setGeometry(QtCore.QRect(70, 160, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btUpdate.setFont(font)
        self.btUpdate.setObjectName("btUpdate")
        self.btSave = QtWidgets.QPushButton(self.groupBox)
        self.btSave.setGeometry(QtCore.QRect(70, 220, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btSave.setFont(font)
        self.btSave.setObjectName("btSave")
        self.btAddNew = QtWidgets.QPushButton(self.groupBox)
        self.btAddNew.setGeometry(QtCore.QRect(70, 40, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btAddNew.setFont(font)
        self.btAddNew.setObjectName("btAddNew")
        self.btClose = QtWidgets.QPushButton(self.groupBox)
        self.btClose.setGeometry(QtCore.QRect(70, 310, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btClose.setFont(font)
        self.btClose.setObjectName("btClose")
        self.btClear = QtWidgets.QPushButton(self.groupBox)
        self.btClear.setGeometry(QtCore.QRect(70, 270, 93, 28))
        self.btClear.setObjectName("btClear")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(130, 40, 871, 241))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setItalic(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 310, 961, 451))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.t2_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.t2_2.setGeometry(QtCore.QRect(180, 40, 761, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.t2_2.setFont(font)
        self.t2_2.setObjectName("t2_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 100, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.t1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.t1.setGeometry(QtCore.QRect(180, 90, 761, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.t1.setFont(font)
        self.t1.setObjectName("t1")
        self.t3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.t3.setGeometry(QtCore.QRect(180, 220, 761, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.t3.setFont(font)
        self.t3.setObjectName("t3")
        self.t4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.t4.setGeometry(QtCore.QRect(180, 270, 761, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.t4.setFont(font)
        self.t4.setObjectName("t4")
        self.t5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.t5.setGeometry(QtCore.QRect(180, 320, 761, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.t5.setFont(font)
        self.t5.setObjectName("t5")
        self.t6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.t6.setGeometry(QtCore.QRect(180, 370, 761, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.t6.setFont(font)
        self.t6.setObjectName("t6")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 360, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.t2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.t2.setGeometry(QtCore.QRect(180, 170, 761, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.t2.setFont(font)
        self.t2.setObjectName("t2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(40, 180, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(40, 220, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(40, 270, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(40, 320, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lblMsg = QtWidgets.QLabel(self.centralwidget)
        self.lblMsg.setGeometry(QtCore.QRect(50, 780, 961, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lblMsg.setFont(font)
        self.lblMsg.setObjectName("lblMsg")
        DBWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(DBWindow)
        QtCore.QMetaObject.connectSlotsByName(DBWindow)

    def retranslateUi(self, DBWindow):
        _translate = QtCore.QCoreApplication.translate
        DBWindow.setWindowTitle(_translate("DBWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("DBWindow", "Qptions"))
        self.btDelete.setText(_translate("DBWindow", "DELETE"))
        self.btUpdate.setText(_translate("DBWindow", "UPDATE"))
        self.btSave.setText(_translate("DBWindow", "SAVE"))
        self.btAddNew.setText(_translate("DBWindow", "NEW"))
        self.btClose.setText(_translate("DBWindow", "CLOSE"))
        self.btClear.setText(_translate("DBWindow", "Clear"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DBWindow", "Ques. No."))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DBWindow", "Que. Description"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DBWindow", "1st Option"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("DBWindow", "2nd Option"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("DBWindow", "3rd Option"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("DBWindow", "4th Oprion"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("DBWindow", "Correct Option"))
        self.label_7.setText(_translate("DBWindow", "Question No."))
        self.label_6.setText(_translate("DBWindow", "Ques. Descption"))
        self.label_5.setText(_translate("DBWindow", "Correct Option"))
        self.label.setText(_translate("DBWindow", "Option 1"))
        self.label_2.setText(_translate("DBWindow", "Option 2"))
        self.label_3.setText(_translate("DBWindow", "Option 3"))
        self.label_4.setText(_translate("DBWindow", "Option 4"))
        self.lblMsg.setText(_translate("DBWindow", "text"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DBWindow = QtWidgets.QMainWindow()
    ui = Ui_DBWindow()
    ui.setupUi(DBWindow)
    DBWindow.show()
    sys.exit(app.exec_())
