from PyQt5 import QtCore, QtGui, QtWidgets

class MyLogin(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(559, 294)
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(False)
        self.groupBox.setGeometry(QtCore.QRect(290, 90, 251, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 40, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.t3 = QtWidgets.QLineEdit(self.groupBox)
        self.t3.setGeometry(QtCore.QRect(120, 40, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.t3.setFont(font)
        self.t3.setText("")
        self.t3.setObjectName("t3")
        self.t4 = QtWidgets.QLineEdit(self.groupBox)
        self.t4.setGeometry(QtCore.QRect(120, 80, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.t4.setFont(font)
        self.t4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.t4.setObjectName("t4")
        self.button2 = QtWidgets.QPushButton(self.groupBox)
        self.button2.setGeometry(QtCore.QRect(120, 110, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.button2.setFont(font)
        self.button2.setObjectName("button2")
        self.label2 = QtWidgets.QLabel(self.groupBox)
        self.label2.setGeometry(QtCore.QRect(10, 166, 231, 16))
        self.label2.setText("")
        self.label2.setObjectName("label2")
        self.button2_2 = QtWidgets.QPushButton(self.groupBox)
        self.button2_2.setGeometry(QtCore.QRect(180, 110, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.button2_2.setFont(font)
        self.button2_2.setObjectName("button2_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 90, 261, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.t1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.t1.setGeometry(QtCore.QRect(120, 40, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.t1.setFont(font)
        self.t1.setText("")
        self.t1.setObjectName("t1")
        self.t2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.t2.setGeometry(QtCore.QRect(120, 80, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.t2.setFont(font)
        self.t2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.t2.setObjectName("t2")
        self.button1 = QtWidgets.QPushButton(self.groupBox_2)
        self.button1.setGeometry(QtCore.QRect(120, 110, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.button1.setFont(font)
        self.button1.setObjectName("button1")
        self.label1 = QtWidgets.QLabel(self.groupBox_2)
        self.label1.setGeometry(QtCore.QRect(10, 165, 241, 16))
        self.label1.setText("")
        self.label1.setObjectName("label1")
        self.button1_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.button1_2.setGeometry(QtCore.QRect(190, 110, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.button1_2.setFont(font)
        self.button1_2.setObjectName("button1_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 281, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.rb1 = QtWidgets.QRadioButton(self.groupBox_3)
        self.rb1.setGeometry(QtCore.QRect(10, 24, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.rb1.setFont(font)
        self.rb1.setAutoFillBackground(True)
        self.rb1.setObjectName("rb1")
        self.rb2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.rb2.setGeometry(QtCore.QRect(174, 24, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.rb2.setFont(font)
        self.rb2.setAutoFillBackground(True)
        self.rb2.setObjectName("rb2")
        #Login.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.groupBox.setTitle(_translate("Login", "Login"))
        self.label.setText(_translate("Login", "Email"))
        self.label_2.setText(_translate("Login", "Password"))
        self.button2.setText(_translate("Login", "SignIn"))
        self.button2_2.setText(_translate("Login", "Clear"))
        self.groupBox_2.setTitle(_translate("Login", "Register Yourself"))
        self.label_3.setText(_translate("Login", "Email"))
        self.label_4.setText(_translate("Login", "Password"))
        self.button1.setText(_translate("Login", "Register"))
        self.button1_2.setText(_translate("Login", "Clear"))
        self.groupBox_3.setTitle(_translate("Login", "Choose Your Option"))
        self.rb1.setText(_translate("Login", "Register Yourself"))
        self.rb2.setText(_translate("Login", "Login"))

